version: 2
jobs:
  build:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Curl
          command: |
            apt-get update
            apt-get install -y curl

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      
      - setup_remote_docker

      # run tests!
      - run:
          name: run tests
          command: docker-compose up --build --abort-on-container-exit

      - store_artifacts:
          path: results
          destination: test-reports